name: Security DevOps Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Microsoft Security DevOps Scan
        uses: microsoft/security-devops-action@preview
        with:
          run: msdo run --output-format sarif --output sarif-results.sarif

      - name: Upload SARIF results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sarif-results.sarif
