name: Test SARIF Upload to Azure Monitor

on:
  workflow_dispatch:

jobs:
  test-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send test SARIF to Azure Monitor
        env:
          WORKSPACE_ID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
          WORKSPACE_KEY: ${{ secrets.LOG_ANALYTICS_PRIMARY_KEY }}
        run: |
          FILE=".github/test/test.sarif"
          CONTENT_TYPE="application/json"
          LOG_TYPE="SecurityScan"
          RESOURCE="/api/logs"
          API_VERSION="2016-04-01"
          TIMESTAMP=$(date -u +"%a, %d %b %Y %H:%M:%S GMT")
          FILE_SIZE=$(wc -c < "$FILE")
          STRING_TO_SIGN="POST\n$FILE_SIZE\n$CONTENT_TYPE\nx-ms-date:$TIMESTAMP\n$RESOURCE"

          # Decode the key and generate the signature
          DECODED_KEY=$(echo "$WORKSPACE_KEY" | base64 -d)
          SIGNATURE=$(echo -n "$STRING_TO_SIGN" | openssl dgst -sha256 -mac HMAC -macopt key:$DECODED_KEY -binary | base64)
          AUTH_HEADER="SharedKey $WORKSPACE_ID:$SIGNATURE"

          # Send the SARIF file
          curl -X POST "https://$WORKSPACE_ID.ods.opinsights.azure.com$RESOURCE?api-version=$API_VERSION" \
            -H "Content-Type: $CONTENT_TYPE" \
            -H "Log-Type: $LOG_TYPE" \
            -H "x-ms-date: $TIMESTAMP" \
            -H "Authorization: $AUTH_HEADER" \
            --data-binary @"$FILE"
